name: Build and Push NGINX IMAGES

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # arch: [amd64, arm64]
        arch: [amd64]

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: your_dockerhub/nginx:latest
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
