name: Build and Push Nginx Multi-Arch Image (Alpine)

on:
  # schedule:
  #   - cron: '0 3 * * 0'

  # push:
  #   branches:
  #     - 'main'
  workflow_dispatch:

env:
  DOCKER_REPO: bailangvvking/nginx

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest Nginx version
        id: lastversion
        uses: dvershinin/lastversion-action@v1
        with:
          repository: 'nginx'
          branch: 'stable'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD  }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.scratch
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          push: true
          # 建议使用新的标签，如 -static 或 -scratch
          tags: |
            ${{ env.DOCKER_REPO }}:${{ steps.lastversion.outputs.last_version }}-scratch
            # ${{ env.DOCKER_REPO }}:latest
          build-args: |
            NGINX_VERSION=${{ steps.lastversion.outputs.last_version }}
